stages:
  - build
  - deploy

build:
  stage: build
  image: registry.okd.ucab.edu.ve/images/docker:23
  services:
    - name: registry.okd.ucab.edu.ve/images/docker:23-dind
      alias: docker
  variables:
      DOCKER_HOST: tcp://docker:2376
  script:
    - DOCKER_IMAGE_NAME="registry.okd.ucab.edu.ve/$OKD_PROJECT_NAME/app"
    - DOCKER_IMAGE_TAG="$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA"
    - cat "$OKD_SA_TOKEN" | docker login -u openshift --password-stdin registry.okd.ucab.edu.ve
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG
    - docker tag $DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME:$CI_COMMIT_REF_NAME
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_REF_NAME
  environment:
    name: master

deploy:
  stage: deploy
  image: registry.okd.ucab.edu.ve/images/okd-cli:3.11
  script:
    - oc login https://okd-cluster.ucab.edu.ve:8443 --token="$(cat $OKD_SA_TOKEN)"
    - oc project "$OKD_PROJECT_NAME"
    - export IMAGE_TAG=$CI_COMMIT_SHA
    - make_parameters OKDTemplate.yml -o /tmp/params
    - oc process -f OKDTemplate.yml --param-file=/tmp/params | oc apply -f -
    - oc wait "dc/$APP_NAME" --for condition=available --timeout=300s
  environment:
    name: master
    on_stop: undeploy

undeploy:
  stage: deploy
  image: registry.okd.ucab.edu.ve/images/okd-cli:3.11
  script:
    - oc login https://okd-cluster.ucab.edu.ve:8443 --token="$(cat $OKD_SA_TOKEN)"
    - oc project "$OKD_PROJECT_NAME"
    - oc delete all --selector app="${APP_NAME}"
    - oc delete secret --selector app="${APP_NAME}"
    - oc delete configMap --selector app="${APP_NAME}"
  when: manual
  environment:
    name: master
    action: stop